from src.phaseprop.comps import Comp
from src.phaseprop.const import Const
from src.phaseprop import utility
from src.phaseprop import refs
from src.phaseprop import units

methane = Comp(
    name="methane",
    cas_no="74-82-8",
    formula="CH4",
    mw=Const(
        value=16.0425,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=190.564,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.599, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.0986, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.0115478,
        unit="dimensionless",
        source=refs.dippr,
    ),
    mp=Const(
        value=units.to_si(-182.48, "C"),
        unit=units.to_si_unit("C"),
        source=refs.perry,
    ),
    hfus=Const(
        value=units.to_si(14.03 * 16.0425, "cal/mol"),
        unit=units.to_si_unit("cal/mol"),
        source=refs.perry,
    ),
    pvap_l=utility.RiedelPvap(
        a=39.205,
        b=-1324.4,
        c=-3.4366,
        d=0.000031019,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=90.69,
        t_max=190.56,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=2.9214,
        b=0.28976,
        c=190.56,
        d=0.28881,
        unit="mol/dm3",
        t_unit="K",
        t_min=90.69,
        t_max=190.56,
        source=refs.dippr,
    ),
)

ethane = Comp(
    name="ethane",
    cas_no="74-84-0",
    formula="C2H6",
    mw=Const(
        value=30.069,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=305.32,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.872, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.1455, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.099493,
        unit="dimensionless",
        source=refs.dippr,
    ),
    mp=Const(
        value=units.to_si(-183.23, "C"),
        unit=units.to_si_unit("C"),
        source=refs.perry,
    ),
    hfus=Const(
        value=units.to_si(22.712 * 30.069, "cal/mol"),
        unit=units.to_si_unit("cal/mol"),
        source=refs.perry,
    ),
    pvap_l=utility.RiedelPvap(
        a=51.857,
        b=-2598.7,
        c=-5.1283,
        d=0.000014913,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=90.35,
        t_max=305.32,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=1.9122,
        b=0.27937,
        c=305.32,
        d=0.29187,
        unit="mol/dm3",
        t_unit="K",
        t_min=90.35,
        t_max=305.32,
        source=refs.dippr,
    ),
)

propane = Comp(
    name="propane",
    cas_no="74-98-6",
    formula="C3H8",
    mw=Const(
        value=44.09562,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=369.83,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.248, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.2, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.152291,
        unit="dimensionless",
        source=refs.dippr,
    ),
    mp=Const(
        value=units.to_si(-187.65, "C"),
        unit=units.to_si_unit("C"),
        source=refs.perry,
    ),
    hfus=Const(
        value=units.to_si(19.1 * 44.09562, "cal/mol"),
        unit=units.to_si_unit("cal/mol"),
        source=refs.perry,
    ),
    pvap_l=utility.RiedelPvap(
        a=59.078,
        b=-3492.6,
        c=-6.0669,
        d=0.000010919,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=85.47,
        t_max=369.83,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=1.3757,
        b=0.27453,
        c=369.83,
        d=0.29359,
        unit="mol/dm3",
        t_unit="K",
        t_min=85.47,
        t_max=369.83,
        source=refs.dippr,
    ),
)

n_butane = Comp(
    name="butane",
    cas_no="106-97-8",
    formula="C4H10",
    mw=Const(
        value=58.1222,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=425.12,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.796, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.255, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.200164,
        unit="dimensionless",
        source=refs.dippr,
    ),
    mp=Const(
        value=units.to_si(138.33, "C"),
        unit=units.to_si_unit("C"),
        source=refs.perry,
    ),
    hfus=Const(
        value=units.to_si(19.167 * 58.1222, "cal/mol"),
        unit=units.to_si_unit("cal/mol"),
        source=refs.perry,
    ),
    pvap_l=utility.RiedelPvap(
        a=66.343,
        b=-4363.2,
        c=-7.046,
        d=9.4509 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=134.86,
        t_max=425.12,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=1.0677,
        b=0.27188,
        c=425.12,
        d=0.28688,
        unit="mol/dm3",
        t_unit="K",
        t_min=134.86,
        t_max=425.12,
        source=refs.dippr,
    ),
)

i_butane = Comp(
    name="2-methylpropane",
    cas_no="75-28-5",
    formula="C4H10",
    mw=Const(
        value=58.1222,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=407.8,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.64, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.259, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.183512,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=108.43,
        b=-5039.9,
        c=-15.012,
        d=0.022725,
        e=1.0,
        unit="Pa",
        t_unit="K",
        t_min=113.54,
        t_max=407.8,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=1.0631,
        b=0.27506,
        c=407.8,
        d=0.2758,
        unit="mol/dm3",
        t_unit="K",
        t_min=113.54,
        t_max=407.8,
        source=refs.dippr,
    ),
)

n_pentane = Comp(
    name="pentane",
    cas_no="109-66-0",
    formula="C5H12",
    mw=Const(
        value=72.14878,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=469.7,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.37, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.313, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.251506,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=78.741,
        b=-5420.3,
        c=-8.8253,
        d=9.6171 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=143.42,
        t_max=469.7,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.84947,
        b=0.26726,
        c=469.7,
        d=0.27789,
        unit="mol/dm3",
        t_unit="K",
        t_min=143.42,
        t_max=469.70,
        source=refs.dippr,
    ),
)

i_pentane = Comp(
    name="2-methylbutane",
    cas_no="78-78-4",
    formula="C5H12",
    mw=Const(
        value=72.14878,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=460.4,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.38, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.306, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.227875,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=71.308,
        b=-4976.0,
        c=-7.7169,
        d=8.7271 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=113.25,
        t_max=460.4,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.91991,
        b=0.27815,
        c=460.4,
        d=0.28667,
        unit="mol/dm3",
        t_unit="K",
        t_min=113.25,
        t_max=460.4,
        source=refs.dippr,
    ),
)

n_hexane = Comp(
    name="hexane",
    cas_no="110-54-3",
    formula="C6H14",
    mw=Const(
        value=86.17536,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=507.6,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.025, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.371, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.301261,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=104.65,
        b=-6995.5,
        c=12.702,
        d=0.000012381,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=177.83,
        t_max=507.6,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.70824,
        b=0.26411,
        c=507.6,
        d=0.27537,
        unit="mol/dm3",
        t_unit="K",
        t_min=177.83,
        t_max=507.6,
        source=refs.dippr,
    ),
)

c_hexane = Comp(
    name="cyclohexane",
    cas_no="110-82-7",
    formula="C6H12",
    mw=Const(
        value=84.15948,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=553.8,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.08, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.308, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.208054,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=51.087,
        b=-5226.4,
        c=-4.2278,
        d=9.76 * 10**-18,
        e=6.0,
        unit="Pa",
        t_unit="K",
        t_min=279.6,
        t_max=553.8,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.88998,
        b=0.27376,
        c=553.8,
        d=0.28571,
        unit="mol/dm3",
        t_unit="K",
        t_min=279.69,
        t_max=553.8,
        source=refs.dippr,
    ),
)

benzene = Comp(
    name="benzene",
    cas_no="71-43-2",
    formula="C6H6",
    mw=Const(
        value=78.11184,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=562.05,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.895, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.256, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.2103,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=83.107,
        b=-6486.2,
        c=-9.2194,
        d=6.9844 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=278.68,
        t_max=562.05,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=1.0259,
        b=0.26666,
        c=562.05,
        d=0.28394,
        unit="mol/dm3",
        t_unit="K",
        t_min=278.68,
        t_max=562.05,
        source=refs.dippr,
    ),
)

heptane = Comp(
    name="heptane",
    cas_no="142-82-5",
    formula="C7H16",
    mw=Const(
        value=1234.5,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=540.2,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(2.74, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.428, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.349469,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=87.829,
        b=-6996.4,
        c=-9.8802,
        d=7.2099 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=182.57,
        t_max=540.2,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.61259,
        b=0.26211,
        c=540.2,
        d=0.28141,
        unit="mol/dm3",
        t_unit="K",
        t_min=182.57,
        t_max=540.2,
        source=refs.dippr,
    ),
)

mc_hexane = Comp(
    name="methylcyclohexane",
    cas_no="108-87-2",
    formula="C7H14",
    mw=Const(
        value=98.18606,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=572.1,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.48, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.369, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.236055,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=92.684,
        b=-7080.8,
        c=-10.695,
        d=8.1366 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=146.58,
        t_max=572.1,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.73109,
        b=0.26971,
        c=572.1,
        d=0.29185,
        unit="mol/dm3",
        t_unit="K",
        t_min=146.58,
        t_max=572.1,
        source=refs.dippr,
    ),
)

toluene = Comp(
    name="toluene",
    cas_no="108-88-3",
    formula="C7H8",
    mw=Const(
        value=92.13842,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=591.75,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.108, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.316, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.264012,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=76.945,
        b=-6729.8,
        c=-8.179,
        d=5.3017 * 10**-6,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=178.18,
        t_max=591.75,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.8792,
        b=0.27136,
        c=591.75,
        d=0.29241,
        unit="mol/dm3",
        t_unit="K",
        t_min=178.18,
        t_max=591.75,
        source=refs.dippr,
    ),
)

octane = Comp(
    name="octane",
    cas_no="111-65-9",
    formula="C8H18",
    mw=Const(
        value=114.22852,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=568.7,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(2.49, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.486, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.399552,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=96.084,
        b=-7900.2,
        c=-11.003,
        d=7.1802 * 10**-6,
        e=2,
        unit="Pa",
        t_unit="K",
        t_min=216.38,
        t_max=568.7,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.5266,
        b=0.25693,
        c=568.7,
        d=0.28571,
        unit="mol/dm3",
        t_unit="K",
        t_min=216.38,
        t_max=568.7,
        source=refs.dippr,
    ),
)

nonane = Comp(
    name="nonane",
    cas_no="111-84-2",
    formula="C9H20",
    mw=Const(
        value=128.2551,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=594.6,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(2.29, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.551, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.44346,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=109.35,
        b=-9030.4,
        c=-12.882,
        d=7.8544 * 10**-6,
        e=2,
        unit="Pa",
        t_unit="K",
        t_min=219.66,
        t_max=594.6,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.46321,
        b=0.25444,
        c=594.6,
        d=0.28571,
        unit="mol/dm3",
        t_unit="K",
        t_min=219.66,
        t_max=594.6,
        source=refs.dippr,
    ),
)

decane = Comp(
    name="decane",
    cas_no="124-18-5",
    formula="C10H22",
    mw=Const(
        value=142.48168,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=617.7,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(2.11, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.617, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.492328,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=112.73,
        b=-9749.6,
        c=-13.245,
        d=7.1266 * 10**-6,
        e=2,
        unit="Pa",
        t_unit="K",
        t_min=243.51,
        t_max=617.7,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=0.41084,
        b=0.25175,
        c=617.7,
        d=0.28571,
        unit="mol/dm3",
        t_unit="K",
        t_min=243.51,
        t_max=617.7,
        source=refs.dippr,
    ),
)

nitrogen = Comp(
    name="nitrogen",
    cas_no="7727-37-9",
    formula="N2",
    mw=Const(
        value=28.0134,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=126.2,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(3.4, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.08921, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.0377215,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=58.282,
        b=-1084.1,
        c=-8.3144,
        d=0.044127,
        e=1.0,
        unit="Pa",
        t_unit="K",
        t_min=63.15,
        t_max=126.2,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=3.2091,
        b=0.2861,
        c=126.2,
        d=0.2966,
        unit="mol/dm3",
        t_unit="K",
        t_min=63.15,
        t_max=126.2,
        source=refs.dippr,
    ),
)


argon = Comp(
    name="argon",
    cas_no="7440-37-1",
    formula="Ar",
    mw=Const(
        value=39.948,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=150.86,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.898, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.07459, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.0,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=42.127,
        b=-1093.1,
        c=-4.1425,
        d=0.000057254,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=83.78,
        t_max=150.86,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=3.8469,
        b=0.2881,
        c=150.86,
        d=0.29783,
        unit="mol/dm3",
        t_unit="K",
        t_min=83.78,
        t_max=150.86,
        source=refs.dippr,
    ),
)

carbon_dioxide = Comp(
    name="carbon dioxide",
    cas_no="124-38-9",
    formula="CO2",
    mw=Const(
        value=44.0095,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=304.21,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(7.383, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.094, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.223621,
        unit="dimensionless",
        source=refs.dippr,
    ),
)

carbon_dioxide = Comp(
    name="carbon dioxide",
    cas_no="124-38-9",
    formula="CO2",
    mw=Const(
        value=44.0095,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=304.21,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(7.383, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.094, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.223621,
        unit="dimensionless",
        source=refs.dippr,
    ),
)

hydrogen_sulfide = Comp(
    name="hydrogen sulfide",
    cas_no="6-4-7783",
    formula="H2S",
    mw=Const(
        value=34.08088,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=373.53,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(8.96291, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.0985, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.0941677,
        unit="dimensionless",
        source=refs.dippr,
    ),
)

water = Comp(
    name="water",
    cas_no="",
    formula="H2O",
    mw=Const(
        value=18.01528,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=647.096,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(22.064, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.0559472, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.344861,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=73.649,
        b=-7258.2,
        c=-7.3037,
        d=4.1653 * 10**-6.0,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=273.16,
        t_max=647.1,
        source=refs.dippr,
    ),
    den_l=utility.IAPWSDenL(),
)

methanol = Comp(
    name="methanol",
    cas_no="67-56-1",
    formula="CH3OH",
    mw=Const(
        value=32.04186,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=512.5,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(8.084, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.117, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.565831,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=82.718,
        b=-6904.5,
        c=-8.8622,
        d=7.4664 * 10**-6.0,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=175.47,
        t_max=512.5,
        source=refs.dippr,
    ),
    den_l=utility.DaubertDenL(
        a=2.3267,
        b=0.27073,
        c=512.5,
        d=0.24713,
        unit="mol/dm3",
        t_unit="K",
        t_min=175.47,
        t_max=512.5,
        source=refs.dippr,
    ),
)

acetone = Comp(
    name="acetone",
    cas_no="67-64-1",
    formula="C3H6O",
    mw=Const(
        value=58.07914,
        unit="g/mol",
        source=refs.dippr,
    ),
    tc=Const(
        value=508.2,
        unit="K",
        source=refs.dippr,
    ),
    pc=Const(
        value=units.to_si(4.701, "MPa"),
        unit=units.to_si_unit("MPa"),
        source=refs.dippr,
    ),
    vc=Const(
        value=units.to_si(0.209, "m3/kmol"),
        unit=units.to_si_unit("m3/kmol"),
        source=refs.dippr,
    ),
    acentric=Const(
        value=0.306527,
        unit="dimensionless",
        source=refs.dippr,
    ),
    pvap_l=utility.RiedelPvap(
        a=69.006,
        b=-5599.6,
        c=-7.0985,
        d=6.2237 * 10**-6.0,
        e=2.0,
        unit="Pa",
        t_unit="K",
        t_min=178.45,
        t_max=508.2,
    ),
    den_l=utility.DaubertDenL(
        a=1.2332,
        b=0.25886,
        c=508.2,
        d=0.2913,
        unit="mol/dm3",
        t_unit="K",
        t_min=178.45,
        t_max=508.2,
        source=refs.dippr,
    ),
)
